package la.netco.sgc.persistence.dto;
// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

//import la.netco.core.persistencia.vo.Ciudad;
import la.netco.core.persistencia.vo.Schemas;

/**
 * Alertas generated by hbm2java
 */
@Entity
@Table(name="Alertas"
    ,schema = Schemas.SGC_SCHEMA
)
@NamedQueries({
	@NamedQuery(name = Alertas.NAMED_QUERY_GET_ALERTAS_BY_FORMATO  , query = Alertas.QUERY_GET_ALERTAS_BY_FORMATO),
	@NamedQuery(name = Alertas.NAMED_QUERY_GET_ALERTAS_BY_FORMATO_CORTE  , query = Alertas.QUERY_GET_ALERTAS_BY_FORMATO_CORTE),
	@NamedQuery(name = Alertas.NAMED_QUERY_GET_ALERTAS_BY_CORTE  , query = Alertas.QUERY_GET_ALERTAS_BY_CORTE),
	@NamedQuery(name = Alertas.NAMED_QUERY_GET_ALERTAS_BY_CAMPOS  , query = Alertas.QUERY_GET_ALERTAS_BY_CAMPOS)
}
)
public class Alertas  implements java.io.Serializable {


     private int altCodigo;
     private Operadores operadores;
     private String altDescripcion;
     private String altValorConstante;
     private Formatos formatoOrigen;
     private CortesFormato cortesFormatoOrigen;
     private DetallesFormato detallesFormatoValorOrigen;
     private String altFiltroO;
     private DetallesFormato detallesFormatoOrigen;
     private Integer forCodigoD;
     private Integer fcrCodigoD;
     private Integer detCodigoD;
     private String altFiltroD;
     private Integer detCodigoValorD;
     

    public Alertas() {
    }

	
    public Alertas(int altCodigo) {
        this.altCodigo = altCodigo;
    }
    public Alertas(int altCodigo, Operadores operadores, String altDescripcion, String altValorConstante) {
       this.altCodigo = altCodigo;
       this.operadores = operadores;
       this.altDescripcion = altDescripcion;
       this.altValorConstante = altValorConstante;
    }
   
    @Id    
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="ALT_Codigo", unique=true, nullable=false)
    public int getAltCodigo() {
        return this.altCodigo;
    }
    
    public void setAltCodigo(int altCodigo) {
        this.altCodigo = altCodigo;
    }
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="OPE_Codigo")
    public Operadores getOperadores() {
        return this.operadores;
    }
    
    public void setOperadores(Operadores operadores) {
        this.operadores = operadores;
    }
    
    @Column(name="ALT_Descripcion", length=1000)
    public String getAltDescripcion() {
        return this.altDescripcion;
    }
    
    public void setAltDescripcion(String altDescripcion) {
        this.altDescripcion = altDescripcion;
    }
    
    @Column(name="ALT_ValorConstante", length=100)
    public String getAltValorConstante() {
        return this.altValorConstante;
    }
    
    public void setAltValorConstante(String altValorConstante) {
        this.altValorConstante = altValorConstante;
    }


	/**
	 * @return the formatoOrigen
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FOR_CodigoO")
	public Formatos getFormatoOrigen() {
		return formatoOrigen;
	}


	/**
	 * @param formatoOrigen the formatoOrigen to set
	 */
	public void setFormatoOrigen(Formatos formatoOrigen) {
		this.formatoOrigen = formatoOrigen;
	}


	/**
	 * @return the cortesFormatoOrigen
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FCR_CodigoO")
	public CortesFormato getCortesFormatoOrigen() {
		return cortesFormatoOrigen;
	}


	/**
	 * @param cortesFormatoOrigen the cortesFormatoOrigen to set
	 */
	public void setCortesFormatoOrigen(CortesFormato cortesFormatoOrigen) {
		this.cortesFormatoOrigen = cortesFormatoOrigen;
	}


	/**
	 * @return the detallesFormatoValorOrigen
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DET_CodigoO")
	public DetallesFormato getDetallesFormatoValorOrigen() {
		return detallesFormatoValorOrigen;
	}


	/**
	 * @param detallesFormatoValorOrigen the detallesFormatoValorOrigen to set
	 */
	public void setDetallesFormatoValorOrigen(
			DetallesFormato detallesFormatoValorOrigen) {
		this.detallesFormatoValorOrigen = detallesFormatoValorOrigen;
	}


	/**
	 * @return the altFiltroO
	 */
    @Column(name="ALT_FiltroO", length=500)
	public String getAltFiltroO() {
		return altFiltroO;
	}


	/**
	 * @param altFiltroO the altFiltroO to set
	 */
	public void setAltFiltroO(String altFiltroO) {
		this.altFiltroO = altFiltroO;
	}


	/**
	 * @return the detallesFormatoOrigen
	 */
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="DET_CodigoValorO")
	public DetallesFormato getDetallesFormatoOrigen() {
		return detallesFormatoOrigen;
	}


	/**
	 * @param detallesFormatoOrigen the detallesFormatoOrigen to set
	 */
	public void setDetallesFormatoOrigen(DetallesFormato detallesFormatoOrigen) {
		this.detallesFormatoOrigen = detallesFormatoOrigen;
	}


	/**
	 * @return the forCodigoD
	 */
	@Column(name="FOR_CodigoD", precision=4)
	public Integer getForCodigoD() {
		return forCodigoD;
	}


	/**
	 * @param forCodigoD the forCodigoD to set
	 */
	public void setForCodigoD(Integer forCodigoD) {
		this.forCodigoD = forCodigoD;
	}


	/**
	 * @return the fcrCodigoD
	 */
	@Column(name="FCR_CodigoD", precision=4)
	public Integer getFcrCodigoD() {
		return fcrCodigoD;
	}


	/**
	 * @param fcrCodigoD the fcrCodigoD to set
	 */
	public void setFcrCodigoD(Integer fcrCodigoD) {
		this.fcrCodigoD = fcrCodigoD;
	}


	/**
	 * @return the detCodigoD
	 */
	@Column(name="DET_CodigoD", precision=4)
	public Integer getDetCodigoD() {
		return detCodigoD;
	}


	/**
	 * @param detCodigoD the detCodigoD to set
	 */
	public void setDetCodigoD(Integer detCodigoD) {
		this.detCodigoD = detCodigoD;
	}


	/**
	 * @return the altFiltroD
	 */
	@Column(name="ALT_FiltroD", length=500)
	public String getAltFiltroD() {
		return altFiltroD;
	}


	/**
	 * @param altFiltroD the altFiltroD to set
	 */
	public void setAltFiltroD(String altFiltroD) {
		this.altFiltroD = altFiltroD;
	}


	/**
	 * @return the detCodigoValorD
	 */
	@Column(name="DET_CodigoValorD", precision=4)
	public Integer getDetCodigoValorD() {
		return detCodigoValorD;
	}


	/**
	 * @param detCodigoValorD the detCodigoValorD to set
	 */
	public void setDetCodigoValorD(Integer detCodigoValorD) {
		this.detCodigoValorD = detCodigoValorD;
	}


	public static final String NAMED_QUERY_GET_ALERTAS_BY_FORMATO   = "getAlertasByFormato";
	public static final String QUERY_GET_ALERTAS_BY_FORMATO 		= "FROM Alertas a WHERE a.formatoOrigen.forCodigo = ?";
	
	public static final String NAMED_QUERY_GET_ALERTAS_BY_FORMATO_CORTE   = "getAlertasByFormatoCorte";
	public static final String QUERY_GET_ALERTAS_BY_FORMATO_CORTE 		= "FROM Alertas a WHERE a.formatoOrigen.forCodigo = ? and a.cortesFormatoOrigen.fcrCodigo = ?";
	
	public static final String NAMED_QUERY_GET_ALERTAS_BY_CORTE   = "getAlertasByCorte";
	public static final String QUERY_GET_ALERTAS_BY_CORTE 		= "FROM Alertas a WHERE a.cortesFormatoOrigen.fcrCodigo = :codCorte or a.fcrCodigoD = :codCorte";
	
	public static final String NAMED_QUERY_GET_ALERTAS_BY_CAMPOS   = "getAlertasByCampos";
	public static final String QUERY_GET_ALERTAS_BY_CAMPOS 		= "FROM Alertas a WHERE a.detallesFormatoValorOrigen.detCodigo = :codDetalle or a.detallesFormatoOrigen.detCodigo = :codDetalle or a.detCodigoD = :codDetalle or a.detCodigoValorD = :codDetalle";
}


