package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import la.netco.core.persistencia.vo.Schemas;

/**
 * Autorizaciones generated by hbm2java
 */
@Entity
@Table(name = "Autorizaciones"
		, schema = Schemas.SGC_SCHEMA)
@NamedQueries({
		@NamedQuery(name = Autorizaciones.NAMED_QUERY_GET_AUTORIZACIONES_BY_FORMATO, query = Autorizaciones.QUERY_GET_AUTORIZACIONES_BY_FORMATO),
		@NamedQuery(name = Autorizaciones.NAMED_QUERY_GET_AUTORIZACIONES_BY_FORMATO_ENTIDADES_VIGENTE, query = Autorizaciones.QUERY_GET_AUTORIZACIONES_BY_FORMATO_ENTIDADES)
})
public class Autorizaciones implements Serializable {

	private Integer autCodigo;
	private String autJustificacion;
	private Date autFechaCreacion;
	private Formatos formatos;
	private Entidades entidades;

	public static final String NAMED_QUERY_GET_AUTORIZACIONES_BY_FORMATO = "getAutorizacionesByFormato";
	public static final String QUERY_GET_AUTORIZACIONES_BY_FORMATO = "FROM Autorizaciones a WHERE a.formatos.forCodigo = ?";

	public static final String NAMED_QUERY_GET_AUTORIZACIONES_BY_FORMATO_ENTIDADES_VIGENTE = "getAutorizacionesByFormatoEntidadVigente";
	public static final String QUERY_GET_AUTORIZACIONES_BY_FORMATO_ENTIDADES = "FROM Autorizaciones a WHERE a.formatos.forCodigo = :codFormato and a.entidades.entCodigo = :entCod and a.autFechaCreacion between :fechaInicial and :fechaFinal";

	/**
	 * Default Constructor
	 */
	public Autorizaciones() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * Minimun Constructor
	 */
	public Autorizaciones(Integer autCodigo) {
		// TODO Auto-generated constructor stub
		this.autCodigo = autCodigo;
	}

	/**
	 * Full Constructor
	 */
	public Autorizaciones(Integer autCodigo, String autJustificacion, Formatos formatos, Entidades entidades) {
		// TODO Auto-generated constructor stub
		this.autCodigo = autCodigo;
		this.autJustificacion = autJustificacion;
		this.formatos = formatos;
		this.entidades = entidades;
	}

	/**
	 * @return the autCodigo
	 */
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "AUT_Codigo", unique = true, nullable = false)
	public Integer getAutCodigo() {
		return this.autCodigo;
	}

	/**
	 * @param autCodigo
	 *            the autCodigo to set
	 */
	public void setAutCodigo(Integer autCodigo) {
		this.autCodigo = autCodigo;
	}

	/**
	 * @return the autJustificacion
	 */
	@Column(name = "AUT_Justificacion", length = 2000)
	public String getAutJustificacion() {
		return this.autJustificacion;
	}

	/**
	 * @param autJustificacion
	 *            the autJustificacion to set
	 */
	public void setAutJustificacion(String autJustificacion) {
		this.autJustificacion = autJustificacion;
	}

	/**
	 * @return the formatos
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FOR_Codigo")
	public Formatos getFormatos() {
		return this.formatos;
	}

	/**
	 * @param formatos
	 *            the formatos to set
	 */
	public void setFormatos(Formatos formatos) {
		this.formatos = formatos;
	}

	/**
	 * @return the entidades
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ENT_Codigo")
	public Entidades getEntidades() {
		return this.entidades;
	}

	/**
	 * @param entidades
	 *            the entidades to set
	 */
	public void setEntidades(Entidades entidades) {
		this.entidades = entidades;
	}

	/**
	 * @return the autFechaCreacion
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "AUT_FechaCreacion", nullable = true)
	public Date getAutFechaCreacion() {
		return autFechaCreacion;
	}

	/**
	 * @param autFechaCreacion
	 *            the autFechaCreacion to set
	 */
	public void setAutFechaCreacion(Date autFechaCreacion) {
		this.autFechaCreacion = autFechaCreacion;
	}

}
