package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import la.netco.core.persistencia.vo.Schemas;

/**
 * DetallesFormato generated by hbm2java
 */
@Entity
@Table(name = "Detalles_Formato", schema = Schemas.SGC_SCHEMA)
@NamedQueries(value = { @NamedQuery(name = DetallesFormato.NAMED_QUERY_DETALLE_FORMATO_POR_FORMATO, query = DetallesFormato.QUERY_DETALLE_FORMATO_POR_FORMATO) })
public class DetallesFormato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6329799264439278700L;
	private int detCodigo;
	private Formatos formatos;
	private String detDescripcion;
	private Integer tpdCodigo;
	private Integer ftdCodigo;
	private Integer detPosicion;
	private String detNombre;
	private Boolean detRequerido;
	private Set<RegistroCargue> registroCargues = new HashSet<RegistroCargue>(0);
	private Set<RegistroCargueHistorico> registroCargueHistoricos = new HashSet<RegistroCargueHistorico>(
			0);

	public DetallesFormato() {
	}

	public DetallesFormato(int detCodigo) {
		this.detCodigo = detCodigo;
	}

	public DetallesFormato(int detCodigo, Formatos formatos,
			String detDescripcion, Integer tpdCodigo, Integer ftdCodigo,
			Integer detPosicion, String detNombre, Boolean detRequerido,
			Set<RegistroCargue> registroCargues,
			Set<RegistroCargueHistorico> registroCargueHistoricos) {
		this.detCodigo = detCodigo;
		this.formatos = formatos;
		this.detDescripcion = detDescripcion;
		this.tpdCodigo = tpdCodigo;
		this.ftdCodigo = ftdCodigo;
		this.detPosicion = detPosicion;
		this.detNombre = detNombre;
		this.detRequerido = detRequerido;
		this.registroCargues = registroCargues;
		this.registroCargueHistoricos = registroCargueHistoricos;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "DET_Codigo", unique = true, nullable = false)
	public int getDetCodigo() {
		return this.detCodigo;
	}

	public void setDetCodigo(int detCodigo) {
		this.detCodigo = detCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FOR_Codigo")
	public Formatos getFormatos() {
		return this.formatos;
	}

	public void setFormatos(Formatos formatos) {
		this.formatos = formatos;
	}

	@Column(name = "DET_Descripcion", length = 1000)
	public String getDetDescripcion() {
		return this.detDescripcion;
	}

	public void setDetDescripcion(String detDescripcion) {
		this.detDescripcion = detDescripcion;
	}

	@Column(name = "TPD_Codigo")
	public Integer getTpdCodigo() {
		return this.tpdCodigo;
	}

	public void setTpdCodigo(Integer tpdCodigo) {
		this.tpdCodigo = tpdCodigo;
	}

	@Column(name = "FTD_Codigo")
	public Integer getFtdCodigo() {
		return this.ftdCodigo;
	}

	public void setFtdCodigo(Integer ftdCodigo) {
		this.ftdCodigo = ftdCodigo;
	}

	@Column(name = "DET_Posicion")
	public Integer getDetPosicion() {
		return this.detPosicion;
	}

	public void setDetPosicion(Integer detPosicion) {
		this.detPosicion = detPosicion;
	}

	@Column(name = "DET_Nombre", length = 200)
	public String getDetNombre() {
		return this.detNombre;
	}

	public void setDetNombre(String detNombre) {
		this.detNombre = detNombre;
	}

	@Column(name = "DET_Requerido")
	public Boolean getDetRequerido() {
		return this.detRequerido;
	}

	public void setDetRequerido(Boolean detRequerido) {
		this.detRequerido = detRequerido;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detallesFormato")
	public Set<RegistroCargue> getRegistroCargues() {
		return this.registroCargues;
	}

	public void setRegistroCargues(Set<RegistroCargue> registroCargues) {
		this.registroCargues = registroCargues;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "detallesFormato")
	public Set<RegistroCargueHistorico> getRegistroCargueHistoricos() {
		return this.registroCargueHistoricos;
	}

	public void setRegistroCargueHistoricos(
			Set<RegistroCargueHistorico> registroCargueHistoricos) {
		this.registroCargueHistoricos = registroCargueHistoricos;
	}
	
	public static final String NAMED_QUERY_DETALLE_FORMATO_POR_FORMATO = "getDetalleFormatoByFormato";
	public static final String QUERY_DETALLE_FORMATO_POR_FORMATO = "from DetallesFormato df where df.formatos.forCodigo = :codigoFormato order by df.detPosicion";

}
