package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import la.netco.core.persistencia.vo.Schemas;

/**
 * FormatosTiposDato generated by hbm2java
 */
@Entity
@Table(name = "Formatos_TiposDato", schema = Schemas.SGC_SCHEMA)
@NamedQueries({
	@NamedQuery(name = FormatosTiposDato.TOMAR_FORMATOS_TIPOS_DATO_POR_TIPO_DATO  , query = FormatosTiposDato.QUERY_TOMAR_FORMATOS_TIPOS_DATO_POR_TIPO_DATO  )
}
)
public class FormatosTiposDato implements java.io.Serializable {

	private int ftdCodigo;
	private TiposDato tiposDato;
	private String ftdFormato;
	private String ftdEjemplo;
	
	public static final String TOMAR_FORMATOS_TIPOS_DATO_POR_TIPO_DATO = "getFormatosTiposDatobyTiposDato";
	public static final String QUERY_TOMAR_FORMATOS_TIPOS_DATO_POR_TIPO_DATO = "from FormatosTiposDato f where f.tiposDato.tpdCodigo = ?";

	public FormatosTiposDato() {
	}

	public FormatosTiposDato(int ftdCodigo) {
		this.ftdCodigo = ftdCodigo;
	}

	public FormatosTiposDato(int ftdCodigo, TiposDato tiposDato,
			String ftdFormato, String ftdEjemplo) {
		this.ftdCodigo = ftdCodigo;
		this.tiposDato = tiposDato;
		this.ftdFormato = ftdFormato;
		this.ftdEjemplo = ftdEjemplo;
	}

	@Id
	@Column(name = "FTD_Codigo", unique = true, nullable = false)
	public int getFtdCodigo() {
		return this.ftdCodigo;
	}

	public void setFtdCodigo(int ftdCodigo) {
		this.ftdCodigo = ftdCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPD_Codigo")
	public TiposDato getTiposDato() {
		return this.tiposDato;
	}

	public void setTiposDato(TiposDato tiposDato) {
		this.tiposDato = tiposDato;
	}

	@Column(name = "FTD_Formato", length = 100)
	public String getFtdFormato() {
		return this.ftdFormato;
	}

	public void setFtdFormato(String ftdFormato) {
		this.ftdFormato = ftdFormato;
	}

	@Column(name = "FTD_Ejemplo", length = 500)
	public String getFtdEjemplo() {
		return this.ftdEjemplo;
	}

	public void setFtdEjemplo(String ftdEjemplo) {
		this.ftdEjemplo = ftdEjemplo;
	}

}
