package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import la.netco.core.persistencia.vo.Schemas;

/**
 * RegistroCargue generated by hbm2java
 * 
 */
@Entity
@Table(name = "Registro_Cargue", schema = Schemas.SGC_SCHEMA)
@NamedQueries({
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_CUENTA, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_CUENTA),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_VALOR, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_VALOR),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_REG, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_REG),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_CORTE, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_CORTE),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_BY_CAMPO, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_BY_CAMPO),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_FOR_REP, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_FOR_REP),
		@NamedQuery(name = RegistroCargue.NAMED_QUERY_GET_REGISTRO_CARGUE_FOR_REPDOS, query = RegistroCargue.QUERY_GET_REGISTRO_CARGUE_FOR_REPDOS)
})
public class RegistroCargue implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int crgCodigo;
	private DetallesFormato detallesFormato;
	private Formatos formatos;
	private CortesFormato cortesFormato;
	private String crgValor;
	private Integer crgNoRegistro;
	private Integer entCodigo;

	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO = "getRegistroCargueByFormatos";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO = "from RegistroCargue r where r.formatos.forCodigo = ?";

	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE = "getRegistroCargueByFormatosEntidadCorte";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE = "from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo";
	
	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_CUENTA = "getRegistroCargueByFormatosEntidadCorteCuenta";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_CUENTA = "from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo and r.crgNoRegistro in (select r.crgNoRegistro from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo and r.detallesFormato.formatos.forCodigo=:codFormato and r.detallesFormato.detDescripcion=:valor and r.crgValor = :valor1)";

	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_VALOR = "getRegistroCargueByFormatosEntidadCorteDetValor";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_VALOR = "from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo and r.detallesFormato.detCodigo = :detCod and r.crgValor = :valor";
	
	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_REG = "getRegistroCargueByFormatosEntidadCorteDetReg";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET_REG = "from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo and r.detallesFormato.detCodigo = :detCod and r.crgNoRegistro = :reg";

	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET = "getRegistroCargueByFormatosEntidadCorteDet";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_FORMATO_ENTIDAD_CORTE_DET = "from RegistroCargue r where r.formatos.forCodigo = :codFormato and r.cortesFormato.fcrCodigo = :codCorte and r.entCodigo = :entCodigo and r.detallesFormato.detCodigo = :detCod";

	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_CORTE = "getRegistroCargueByCorte";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_CORTE = "from RegistroCargue r where r.cortesFormato.fcrCodigo = ?";
	
	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_BY_CAMPO = "getRegistroCargueByCampo";
	public static final String QUERY_GET_REGISTRO_CARGUE_BY_CAMPO = "from RegistroCargue r where r.detallesFormato.detCodigo = ?";
	
	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_FOR_REP = "getRegistroCargueByRep";
	public static final String QUERY_GET_REGISTRO_CARGUE_FOR_REP = "SELECT r.crgNoRegistro FROM RegistroCargue r where r.formatos.forCodigo = ? and r.entCodigo = ? and r.crgValor = ?  and  r.cortesFormato.fcrCodigo = ? ";
	
	public static final String NAMED_QUERY_GET_REGISTRO_CARGUE_FOR_REPDOS = "getRegistroCargueByRepDos";
	public static final String QUERY_GET_REGISTRO_CARGUE_FOR_REPDOS = "SELECT  r.crgValor  FROM RegistroCargue r where r.formatos.forCodigo = ? and r.entCodigo = ? and  r.cortesFormato.fcrCodigo = ? and r.crgNoRegistro = ? and r.detallesFormato.detCodigo = ? ";
	
	
	public RegistroCargue() {
	}

	public RegistroCargue(int crgCodigo) {
		this.crgCodigo = crgCodigo;
	}

	public RegistroCargue(int crgCodigo, DetallesFormato detallesFormato, Formatos formatos, CortesFormato cortesFormato, String crgValor,
			Integer crgNoRegistro, Integer entCodigo) {
		this.crgCodigo = crgCodigo;
		this.detallesFormato = detallesFormato;
		this.formatos = formatos;
		this.cortesFormato = cortesFormato;
		this.crgValor = crgValor;
		this.crgNoRegistro = crgNoRegistro;
		this.entCodigo = entCodigo;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "CRG_Codigo", unique = true, nullable = false)
	public int getCrgCodigo() {
		return this.crgCodigo;
	}

	public void setCrgCodigo(int crgCodigo) {
		this.crgCodigo = crgCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DET_Codigo")
	public DetallesFormato getDetallesFormato() {
		return this.detallesFormato;
	}

	public void setDetallesFormato(DetallesFormato detallesFormato) {
		this.detallesFormato = detallesFormato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FOR_Codigo")
	public Formatos getFormatos() {
		return this.formatos;
	}

	public void setFormatos(Formatos formatos) {
		this.formatos = formatos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCR_Codigo")
	public CortesFormato getCortesFormato() {
		return this.cortesFormato;
	}

	public void setCortesFormato(CortesFormato cortesFormato) {
		this.cortesFormato = cortesFormato;
	}

	@Column(name = "CRG_Valor", length = 1000)
	public String getCrgValor() {
		return this.crgValor;
	}

	public void setCrgValor(String crgValor) {
		this.crgValor = crgValor;
	}

	@Column(name = "CRG_NoRegistro")
	public Integer getCrgNoRegistro() {
		return this.crgNoRegistro;
	}

	public void setCrgNoRegistro(Integer crgNoRegistro) {
		this.crgNoRegistro = crgNoRegistro;
	}

	@Column(name = "ENT_Codigo")
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

}
