package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import la.netco.core.persistencia.vo.Schemas;

/**
 * RegistroCargueHistorico generated by hbm2java
 */
@Entity
@Table(name = "Registro_Cargue_Historico", schema = Schemas.SGC_SCHEMA)
public class RegistroCargueHistorico implements java.io.Serializable {

	private int crgCodigo;
	private DetallesFormato detallesFormato;
	private Formatos formatos;
	private CortesFormato cortesFormato;
	private String crgValor;
	private Integer crgNoRegistro;
	private Integer entCodigo;

	public RegistroCargueHistorico() {
	}

	public RegistroCargueHistorico(int crgCodigo) {
		this.crgCodigo = crgCodigo;
	}

	public RegistroCargueHistorico(int crgCodigo,
			DetallesFormato detallesFormato, Formatos formatos,
			CortesFormato cortesFormato, String crgValor,
			Integer crgNoRegistro, Integer entCodigo) {
		this.crgCodigo = crgCodigo;
		this.detallesFormato = detallesFormato;
		this.formatos = formatos;
		this.cortesFormato = cortesFormato;
		this.crgValor = crgValor;
		this.crgNoRegistro = crgNoRegistro;
		this.entCodigo = entCodigo;
	}

	@Id
	@Column(name = "CRG_Codigo", unique = true, nullable = false)
	public int getCrgCodigo() {
		return this.crgCodigo;
	}

	public void setCrgCodigo(int crgCodigo) {
		this.crgCodigo = crgCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DET_Codigo")
	public DetallesFormato getDetallesFormato() {
		return this.detallesFormato;
	}

	public void setDetallesFormato(DetallesFormato detallesFormato) {
		this.detallesFormato = detallesFormato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FOR_Codigo")
	public Formatos getFormatos() {
		return this.formatos;
	}

	public void setFormatos(Formatos formatos) {
		this.formatos = formatos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCR_Codigo")
	public CortesFormato getCortesFormato() {
		return this.cortesFormato;
	}

	public void setCortesFormato(CortesFormato cortesFormato) {
		this.cortesFormato = cortesFormato;
	}

	@Column(name = "CRG_Valor", length = 1000)
	public String getCrgValor() {
		return this.crgValor;
	}

	public void setCrgValor(String crgValor) {
		this.crgValor = crgValor;
	}

	@Column(name = "CRG_NoRegistro")
	public Integer getCrgNoRegistro() {
		return this.crgNoRegistro;
	}

	public void setCrgNoRegistro(Integer crgNoRegistro) {
		this.crgNoRegistro = crgNoRegistro;
	}

	@Column(name = "ENT_Codigo")
	public Integer getEntCodigo() {
		return this.entCodigo;
	}

	public void setEntCodigo(Integer entCodigo) {
		this.entCodigo = entCodigo;
	}

}
