package la.netco.sgc.persistence.dto;

// Generated 25/10/2012 08:58:29 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import la.netco.core.persistencia.vo.Schemas;

/**
 * TiposDato generated by hbm2java
 */
@Entity
@Table(name = "Tipos_Dato", schema = Schemas.SGC_SCHEMA)
public class TiposDato implements java.io.Serializable {

	private int tpdCodigo;
	private String tpdDescripcion;
	private String tpdMapeo;
	private Set<FormatosTiposDato> formatosTiposDatos = new HashSet<FormatosTiposDato>(
			0);

	public TiposDato() {
	}

	public TiposDato(int tpdCodigo) {
		this.tpdCodigo = tpdCodigo;
	}

	public TiposDato(int tpdCodigo, String tpdDescripcion,
			Set<FormatosTiposDato> formatosTiposDatos) {
		this.tpdCodigo = tpdCodigo;
		this.tpdDescripcion = tpdDescripcion;
		this.formatosTiposDatos = formatosTiposDatos;
	}

	@Id
	@Column(name = "TPD_Codigo", unique = true, nullable = false)
	public int getTpdCodigo() {
		return this.tpdCodigo;
	}

	public void setTpdCodigo(int tpdCodigo) {
		this.tpdCodigo = tpdCodigo;
	}

	@Column(name = "TPD_Descripcion", length = 100)
	public String getTpdDescripcion() {
		return this.tpdDescripcion;
	}

	public void setTpdDescripcion(String tpdDescripcion) {
		this.tpdDescripcion = tpdDescripcion;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tiposDato")
	public Set<FormatosTiposDato> getFormatosTiposDatos() {
		return this.formatosTiposDatos;
	}

	public void setFormatosTiposDatos(Set<FormatosTiposDato> formatosTiposDatos) {
		this.formatosTiposDatos = formatosTiposDatos;
	}

	/**
	 * @return the tpdMapeo
	 */
	@Column(name = "TPD_Mapeo", nullable = true)
	public String getTpdMapeo() {
		return tpdMapeo;
	}

	/**
	 * @param tpdMapeo the tpdMapeo to set
	 */
	public void setTpdMapeo(String tpdMapeo) {
		this.tpdMapeo = tpdMapeo;
	}
	
	

}
