package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

import la.netco.persistencia.dto.commons.Entrada;
import la.netco.persistencia.dto.commons.Expediente;
import la.netco.persistencia.dto.commons.Salida;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name = "ARCHIVO", schema = "dbo", catalog = "AUTOR")
public class Archivo implements java.io.Serializable {

    private int arcId;
    private Salida salida;
    private Expediente expediente;
    private Entrada entrada;
    private String arcNom;
    private String arcFil;

    public Archivo() {
    }

    public Archivo(int arcId) {
        this.arcId = arcId;
    }

    public Archivo(int arcId, Salida salida, Expediente expediente, Entrada entrada, String arcNom, String arcFil) {
        this.arcId = arcId;
        this.salida = salida;
        this.expediente = expediente;
        this.entrada = entrada;
        this.arcNom = arcNom;
        this.arcFil = arcFil;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "ARC_ID", unique = true, nullable = false)
    public int getArcId() {
        return this.arcId;
    }

    public void setArcId(int arcId) {
        this.arcId = arcId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ARC_SAL")
    public Salida getSalida() {
        return this.salida;
    }

    public void setSalida(Salida salida) {
        this.salida = salida;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ARC_EXP")
    public Expediente getExpediente() {
        return this.expediente;
    }

    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ARC_ENT")
    public Entrada getEntrada() {
        return this.entrada;
    }

    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }

    @Column(name = "ARC_NOM")
    public String getArcNom() {
        return this.arcNom;
    }

    public void setArcNom(String arcNom) {
        this.arcNom = arcNom;
    }

    @Column(name = "ARC_FIL")
    public String getArcFil() {
        return this.arcFil;
    }

    public void setArcFil(String arcFil) {
        this.arcFil = arcFil;
    }
}
