package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import java.sql.Blob;
import javax.persistence.*;

import la.netco.persistencia.dto.commons.Entrada;
import la.netco.persistencia.dto.commons.Expediente;
import la.netco.persistencia.dto.commons.Salida;

/**
 * Imagenes generated by hbm2java
 */
@Entity
@Table(name = "IMAGENES", schema = "dbo", catalog = "AUTOR")
public class Imagenes implements java.io.Serializable {

    private int imgId;
    private Entrada entrada;
    private Expediente expediente;
    private Salida salida;
    private String imgNom;
    private Blob imgImg;

    public Imagenes() {
    }

    public Imagenes(int imgId) {
        this.imgId = imgId;
    }

    public Imagenes(int imgId, Entrada entrada, Expediente expediente, Salida salida, String imgNom, Blob imgImg) {
        this.imgId = imgId;
        this.entrada = entrada;
        this.expediente = expediente;
        this.salida = salida;
        this.imgNom = imgNom;
        this.imgImg = imgImg;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "IMG_ID", unique = true, nullable = false)
    public int getImgId() {
        return this.imgId;
    }

    public void setImgId(int imgId) {
        this.imgId = imgId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IMG_ENT")
    public Entrada getEntrada() {
        return this.entrada;
    }

    public void setEntrada(Entrada entrada) {
        this.entrada = entrada;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IMG_EXP")
    public Expediente getExpediente() {
        return this.expediente;
    }

    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "IMG_SAL")
    public Salida getSalida() {
        return this.salida;
    }

    public void setSalida(Salida salida) {
        this.salida = salida;
    }

    @Column(name = "IMG_NOM", length = 100)
    public String getImgNom() {
        return this.imgNom;
    }

    public void setImgNom(String imgNom) {
        this.imgNom = imgNom;
    }

    @Column(name = "IMG_IMG")
    public Blob getImgImg() {
        return this.imgImg;
    }

    public void setImgImg(Blob imgImg) {
        this.imgImg = imgImg;
    }
}
