package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

/**
 * Informes generated by hbm2java
 */
@Entity
@Table(name = "INFORMES", schema = "dbo", catalog = "AUTOR")
public class Informes implements java.io.Serializable {

    private int infId;
    private String infNoo;
    private String infNoa;
    private String infDes;

    public Informes() {
    }

    public Informes(int infId) {
        this.infId = infId;
    }

    public Informes(int infId, String infNoo, String infNoa, String infDes) {
        this.infId = infId;
        this.infNoo = infNoo;
        this.infNoa = infNoa;
        this.infDes = infDes;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "INF_ID", unique = true, nullable = false)
    public int getInfId() {
        return this.infId;
    }

    public void setInfId(int infId) {
        this.infId = infId;
    }

    @Column(name = "INF_NOO", length = 200)
    public String getInfNoo() {
        return this.infNoo;
    }

    public void setInfNoo(String infNoo) {
        this.infNoo = infNoo;
    }

    @Column(name = "INF_NOA", length = 200)
    public String getInfNoa() {
        return this.infNoa;
    }

    public void setInfNoa(String infNoa) {
        this.infNoa = infNoa;
    }

    @Column(name = "INF_DES")
    public String getInfDes() {
        return this.infDes;
    }

    public void setInfDes(String infDes) {
        this.infDes = infDes;
    }
}
