package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.*;

/**
 * Maestropersonas generated by hbm2java
 */
@Entity
@Table(name = "MAESTROPERSONAS", schema = "dbo", catalog = "AUTOR")
public class Maestropersonas implements java.io.Serializable {

    private int perId;
    private Short perTdo;
    private String perDoc;
    private Short perNac;
    private String perNom;
    private String perPap;
    private String perSap;
    private Date perFna;
    private String perDir;
    private Short perLug;
    private String perTl1;
    private String perTl2;
    private String perTl3;
    private String perFax;
    private String perCe1;
    private String perCe2;
    private Character perSexo;
    private Short perNedu;
    private String perUsu;
    private String perPwd;
    private String perCfav;
    private String perOcdom;

    public Maestropersonas() {
    }

    public Maestropersonas(int perId, String perDoc, String perUsu) {
        this.perId = perId;
        this.perDoc = perDoc;
        this.perUsu = perUsu;
    }

    public Maestropersonas(int perId, Short perTdo, String perDoc, Short perNac, String perNom, String perPap, String perSap, Date perFna, String perDir, Short perLug, String perTl1, String perTl2, String perTl3, String perFax, String perCe1, String perCe2, Character perSexo, Short perNedu, String perUsu, String perPwd, String perCfav, String perOcdom) {
        this.perId = perId;
        this.perTdo = perTdo;
        this.perDoc = perDoc;
        this.perNac = perNac;
        this.perNom = perNom;
        this.perPap = perPap;
        this.perSap = perSap;
        this.perFna = perFna;
        this.perDir = perDir;
        this.perLug = perLug;
        this.perTl1 = perTl1;
        this.perTl2 = perTl2;
        this.perTl3 = perTl3;
        this.perFax = perFax;
        this.perCe1 = perCe1;
        this.perCe2 = perCe2;
        this.perSexo = perSexo;
        this.perNedu = perNedu;
        this.perUsu = perUsu;
        this.perPwd = perPwd;
        this.perCfav = perCfav;
        this.perOcdom = perOcdom;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "PER_ID", unique = true, nullable = false)
    public int getPerId() {
        return this.perId;
    }

    public void setPerId(int perId) {
        this.perId = perId;
    }

    @Column(name = "PER_TDO")
    public Short getPerTdo() {
        return this.perTdo;
    }

    public void setPerTdo(Short perTdo) {
        this.perTdo = perTdo;
    }

    @Column(name = "PER_DOC", nullable = false, length = 30)
    public String getPerDoc() {
        return this.perDoc;
    }

    public void setPerDoc(String perDoc) {
        this.perDoc = perDoc;
    }

    @Column(name = "PER_NAC")
    public Short getPerNac() {
        return this.perNac;
    }

    public void setPerNac(Short perNac) {
        this.perNac = perNac;
    }

    @Column(name = "PER_NOM", length = 50)
    public String getPerNom() {
        return this.perNom;
    }

    public void setPerNom(String perNom) {
        this.perNom = perNom;
    }

    @Column(name = "PER_PAP", length = 50)
    public String getPerPap() {
        return this.perPap;
    }

    public void setPerPap(String perPap) {
        this.perPap = perPap;
    }

    @Column(name = "PER_SAP", length = 50)
    public String getPerSap() {
        return this.perSap;
    }

    public void setPerSap(String perSap) {
        this.perSap = perSap;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "PER_FNA", length = 23)
    public Date getPerFna() {
        return this.perFna;
    }

    public void setPerFna(Date perFna) {
        this.perFna = perFna;
    }

    @Column(name = "PER_DIR", length = 200)
    public String getPerDir() {
        return this.perDir;
    }

    public void setPerDir(String perDir) {
        this.perDir = perDir;
    }

    @Column(name = "PER_LUG")
    public Short getPerLug() {
        return this.perLug;
    }

    public void setPerLug(Short perLug) {
        this.perLug = perLug;
    }

    @Column(name = "PER_TL1", length = 50)
    public String getPerTl1() {
        return this.perTl1;
    }

    public void setPerTl1(String perTl1) {
        this.perTl1 = perTl1;
    }

    @Column(name = "PER_TL2", length = 50)
    public String getPerTl2() {
        return this.perTl2;
    }

    public void setPerTl2(String perTl2) {
        this.perTl2 = perTl2;
    }

    @Column(name = "PER_TL3", length = 50)
    public String getPerTl3() {
        return this.perTl3;
    }

    public void setPerTl3(String perTl3) {
        this.perTl3 = perTl3;
    }

    @Column(name = "PER_FAX", length = 50)
    public String getPerFax() {
        return this.perFax;
    }

    public void setPerFax(String perFax) {
        this.perFax = perFax;
    }

    @Column(name = "PER_CE1", length = 50)
    public String getPerCe1() {
        return this.perCe1;
    }

    public void setPerCe1(String perCe1) {
        this.perCe1 = perCe1;
    }

    @Column(name = "PER_CE2", length = 50)
    public String getPerCe2() {
        return this.perCe2;
    }

    public void setPerCe2(String perCe2) {
        this.perCe2 = perCe2;
    }

    @Column(name = "PER_SEXO", length = 1)
    public Character getPerSexo() {
        return this.perSexo;
    }

    public void setPerSexo(Character perSexo) {
        this.perSexo = perSexo;
    }

    @Column(name = "PER_NEDU")
    public Short getPerNedu() {
        return this.perNedu;
    }

    public void setPerNedu(Short perNedu) {
        this.perNedu = perNedu;
    }

    @Column(name = "PER_USU", nullable = false, length = 50)
    public String getPerUsu() {
        return this.perUsu;
    }

    public void setPerUsu(String perUsu) {
        this.perUsu = perUsu;
    }

    @Column(name = "PER_PWD", length = 50)
    public String getPerPwd() {
        return this.perPwd;
    }

    public void setPerPwd(String perPwd) {
        this.perPwd = perPwd;
    }

    @Column(name = "PER_CFAV", length = 50)
    public String getPerCfav() {
        return this.perCfav;
    }

    public void setPerCfav(String perCfav) {
        this.perCfav = perCfav;
    }

    @Column(name = "PER_OCDOM", length = 100)
    public String getPerOcdom() {
        return this.perOcdom;
    }

    public void setPerOcdom(String perOcdom) {
        this.perOcdom = perOcdom;
    }
}
