package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

/**
 * Moneda generated by hbm2java
 */
@Entity
@Table(name = "MONEDA", schema = "dbo", catalog = "AUTOR")
public class Moneda implements java.io.Serializable {

    private short monId;
    private String monNom;

    public Moneda() {
    }

    public Moneda(short monId) {
        this.monId = monId;
    }

    public Moneda(short monId, String monNom) {
        this.monId = monId;
        this.monNom = monNom;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "MON_ID", unique = true, nullable = false)
    public short getMonId() {
        return this.monId;
    }

    public void setMonId(short monId) {
        this.monId = monId;
    }

    @Column(name = "MON_NOM", length = 30)
    public String getMonNom() {
        return this.monNom;
    }

    public void setMonNom(String monNom) {
        this.monNom = monNom;
    }
}
