package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * Objeto generated by hbm2java
 */
@Entity
@Table(name = "OBJETO", schema = "dbo", catalog = "AUTOR")
public class Objeto implements java.io.Serializable {

    private short objId;
    private String objFrm;
    private String objCtr;
    private String objCod;
    private String objNom;
    private Short objNiv;
    private Set<Rolname> rolnames = new HashSet<Rolname>(0);

    public Objeto() {
    }

    public Objeto(short objId) {
        this.objId = objId;
    }

    public Objeto(short objId, String objFrm, String objCtr, String objCod, String objNom, Short objNiv, Set<Rolname> rolnames) {
        this.objId = objId;
        this.objFrm = objFrm;
        this.objCtr = objCtr;
        this.objCod = objCod;
        this.objNom = objNom;
        this.objNiv = objNiv;
        this.rolnames = rolnames;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "OBJ_ID", unique = true, nullable = false)
    public short getObjId() {
        return this.objId;
    }

    public void setObjId(short objId) {
        this.objId = objId;
    }

    @Column(name = "OBJ_FRM", length = 30)
    public String getObjFrm() {
        return this.objFrm;
    }

    public void setObjFrm(String objFrm) {
        this.objFrm = objFrm;
    }

    @Column(name = "OBJ_CTR", length = 30)
    public String getObjCtr() {
        return this.objCtr;
    }

    public void setObjCtr(String objCtr) {
        this.objCtr = objCtr;
    }

    @Column(name = "OBJ_COD", length = 30)
    public String getObjCod() {
        return this.objCod;
    }

    public void setObjCod(String objCod) {
        this.objCod = objCod;
    }

    @Column(name = "OBJ_NOM", length = 50)
    public String getObjNom() {
        return this.objNom;
    }

    public void setObjNom(String objNom) {
        this.objNom = objNom;
    }

    @Column(name = "OBJ_NIV")
    public Short getObjNiv() {
        return this.objNiv;
    }

    public void setObjNiv(Short objNiv) {
        this.objNiv = objNiv;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "ROL", schema = "dbo", catalog = "AUTOR", joinColumns = {
        @JoinColumn(name = "ROL_OBJ", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "ROL_RLN", nullable = false, updatable = false)})
    public Set<Rolname> getRolnames() {
        return this.rolnames;
    }

    public void setRolnames(Set<Rolname> rolnames) {
        this.rolnames = rolnames;
    }
}
