package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import java.sql.Clob;
import java.util.Date;
import javax.persistence.*;

/**
 * Oficios generated by hbm2java
 */
@Entity
@Table(name = "OFICIOS", schema = "dbo", catalog = "AUTOR")
public class Oficios implements java.io.Serializable {

    private int ofcIf;
    private Date ofcFecha;
    private int ofcPerid;
    private String ofcMotivos;
    private String ofcRadicaciones;
    private String ofcFirmante;
    private Clob ofcObservaciones;
    private short ofcTipo;
    private String ofcNroentrada;

    public Oficios() {
    }

    public Oficios(int ofcIf, int ofcPerid, String ofcRadicaciones, short ofcTipo) {
        this.ofcIf = ofcIf;
        this.ofcPerid = ofcPerid;
        this.ofcRadicaciones = ofcRadicaciones;
        this.ofcTipo = ofcTipo;
    }

    public Oficios(int ofcIf, Date ofcFecha, int ofcPerid, String ofcMotivos, String ofcRadicaciones, String ofcFirmante, Clob ofcObservaciones, short ofcTipo, String ofcNroentrada) {
        this.ofcIf = ofcIf;
        this.ofcFecha = ofcFecha;
        this.ofcPerid = ofcPerid;
        this.ofcMotivos = ofcMotivos;
        this.ofcRadicaciones = ofcRadicaciones;
        this.ofcFirmante = ofcFirmante;
        this.ofcObservaciones = ofcObservaciones;
        this.ofcTipo = ofcTipo;
        this.ofcNroentrada = ofcNroentrada;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "OFC_IF", unique = true, nullable = false)
    public int getOfcIf() {
        return this.ofcIf;
    }

    public void setOfcIf(int ofcIf) {
        this.ofcIf = ofcIf;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "OFC_FECHA", length = 23)
    public Date getOfcFecha() {
        return this.ofcFecha;
    }

    public void setOfcFecha(Date ofcFecha) {
        this.ofcFecha = ofcFecha;
    }

    @Column(name = "OFC_PERID", nullable = false)
    public int getOfcPerid() {
        return this.ofcPerid;
    }

    public void setOfcPerid(int ofcPerid) {
        this.ofcPerid = ofcPerid;
    }

    @Column(name = "OFC_MOTIVOS", length = 1000)
    public String getOfcMotivos() {
        return this.ofcMotivos;
    }

    public void setOfcMotivos(String ofcMotivos) {
        this.ofcMotivos = ofcMotivos;
    }

    @Column(name = "OFC_RADICACIONES", nullable = false, length = 250)
    public String getOfcRadicaciones() {
        return this.ofcRadicaciones;
    }

    public void setOfcRadicaciones(String ofcRadicaciones) {
        this.ofcRadicaciones = ofcRadicaciones;
    }

    @Column(name = "OFC_FIRMANTE", length = 150)
    public String getOfcFirmante() {
        return this.ofcFirmante;
    }

    public void setOfcFirmante(String ofcFirmante) {
        this.ofcFirmante = ofcFirmante;
    }

    @Column(name = "OFC_OBSERVACIONES")
    public Clob getOfcObservaciones() {
        return this.ofcObservaciones;
    }

    public void setOfcObservaciones(Clob ofcObservaciones) {
        this.ofcObservaciones = ofcObservaciones;
    }

    @Column(name = "OFC_TIPO", nullable = false)
    public short getOfcTipo() {
        return this.ofcTipo;
    }

    public void setOfcTipo(short ofcTipo) {
        this.ofcTipo = ofcTipo;
    }

    @Column(name = "OFC_NROENTRADA", length = 20)
    public String getOfcNroentrada() {
        return this.ofcNroentrada;
    }

    public void setOfcNroentrada(String ofcNroentrada) {
        this.ofcNroentrada = ofcNroentrada;
    }
}
