package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

import la.netco.persistencia.dto.commons.Entidad;
import la.netco.persistencia.dto.commons.Persona;
import la.netco.persistencia.dto.commons.Registro;
import la.netco.persistencia.dto.commons.Relacioncontrato;
import la.netco.persistencia.dto.commons.Tipospersona;


/**
 * Parteinterviniente generated by hbm2java
 */
@Entity
@Table(name = "PARTEINTERVINIENTE", schema = "dbo", catalog = "AUTOR")
public class Parteinterviniente implements java.io.Serializable {

    private int pinId;
    private Persona persona;
    private Registro registro;
    private Tipospersona tipospersona;
    private Entidad entidad;
    private Relacioncontrato relacioncontrato;

    public Parteinterviniente() {
    }

    public Parteinterviniente(int pinId, Registro registro) {
        this.pinId = pinId;
        this.registro = registro;
    }

    public Parteinterviniente(int pinId, Persona persona, Registro registro, Tipospersona tipospersona, Entidad entidad, Relacioncontrato relacioncontrato) {
        this.pinId = pinId;
        this.persona = persona;
        this.registro = registro;
        this.tipospersona = tipospersona;
        this.entidad = entidad;
        this.relacioncontrato = relacioncontrato;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "PIN_ID", unique = true, nullable = false)
    public int getPinId() {
        return this.pinId;
    }

    public void setPinId(int pinId) {
        this.pinId = pinId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PIN_PER")
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PIN_REG", nullable = false)
    public Registro getRegistro() {
        return this.registro;
    }

    public void setRegistro(Registro registro) {
        this.registro = registro;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PIN_TPE")
    public Tipospersona getTipospersona() {
        return this.tipospersona;
    }

    public void setTipospersona(Tipospersona tipospersona) {
        this.tipospersona = tipospersona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PIN_ETD")
    public Entidad getEntidad() {
        return this.entidad;
    }

    public void setEntidad(Entidad entidad) {
        this.entidad = entidad;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PIN_RCO")
    public Relacioncontrato getRelacioncontrato() {
        return this.relacioncontrato;
    }

    public void setRelacioncontrato(Relacioncontrato relacioncontrato) {
        this.relacioncontrato = relacioncontrato;
    }
}
