package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

import la.netco.core.persistencia.vo.Usuario;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "PERFIL", schema = "dbo", catalog = "AUTOR")
public class Perfil implements java.io.Serializable {

    private short prfCod;
    private String prfNom;
    private Set<Rolname> rolnames = new HashSet<Rolname>(0);
    private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Perfil() {
    }

    public Perfil(short prfCod) {
        this.prfCod = prfCod;
    }

    public Perfil(short prfCod, String prfNom, Set<Rolname> rolnames, Set<Usuario> usuarios) {
        this.prfCod = prfCod;
        this.prfNom = prfNom;
        this.rolnames = rolnames;
        this.usuarios = usuarios;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "PRF_COD", unique = true, nullable = false)
    public short getPrfCod() {
        return this.prfCod;
    }

    public void setPrfCod(short prfCod) {
        this.prfCod = prfCod;
    }

    @Column(name = "PRF_NOM", length = 50)
    public String getPrfNom() {
        return this.prfNom;
    }

    public void setPrfNom(String prfNom) {
        this.prfNom = prfNom;
    }

    @ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinTable(name = "ROLPERFIL", schema = "dbo", catalog = "AUTOR", joinColumns = {
        @JoinColumn(name = "RPF_PRF", nullable = false, updatable = false)}, inverseJoinColumns = {
        @JoinColumn(name = "RPF_RLN", nullable = false, updatable = false)})
    public Set<Rolname> getRolnames() {
        return this.rolnames;
    }

    public void setRolnames(Set<Rolname> rolnames) {
        this.rolnames = rolnames;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "perfil")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }

    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
}
