package la.netco.persistencia.dto.commons.base;
// Generated 9/10/2012 04:26:59 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.*;

import la.netco.persistencia.dto.commons.Persona;
import la.netco.persistencia.dto.commons.Tiposdocumento;

/**
 * Personahistorica generated by hbm2java
 */
@Entity
@Table(name = "PERSONAHISTORICA", schema = "dbo", catalog = "AUTOR")
public class Personahistorica implements java.io.Serializable {

    private int phiId;
    private Persona persona;
    private Tiposdocumento tiposdocumento;
    private String phiDoc;
    private String phiNom;
    private String phiPap;
    private String phiSap;
    private String phiSeunom;

    public Personahistorica() {
    }

    public Personahistorica(int phiId) {
        this.phiId = phiId;
    }

    public Personahistorica(int phiId, Persona persona, Tiposdocumento tiposdocumento, String phiDoc, String phiNom, String phiPap, String phiSap, String phiSeunom) {
        this.phiId = phiId;
        this.persona = persona;
        this.tiposdocumento = tiposdocumento;
        this.phiDoc = phiDoc;
        this.phiNom = phiNom;
        this.phiPap = phiPap;
        this.phiSap = phiSap;
        this.phiSeunom = phiSeunom;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "PHI_ID", unique = true, nullable = false)
    public int getPhiId() {
        return this.phiId;
    }

    public void setPhiId(int phiId) {
        this.phiId = phiId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PHI_PER")
    public Persona getPersona() {
        return this.persona;
    }

    public void setPersona(Persona persona) {
        this.persona = persona;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PHI_TDO")
    public Tiposdocumento getTiposdocumento() {
        return this.tiposdocumento;
    }

    public void setTiposdocumento(Tiposdocumento tiposdocumento) {
        this.tiposdocumento = tiposdocumento;
    }

    @Column(name = "PHI_DOC", length = 30)
    public String getPhiDoc() {
        return this.phiDoc;
    }

    public void setPhiDoc(String phiDoc) {
        this.phiDoc = phiDoc;
    }

    @Column(name = "PHI_NOM", length = 50)
    public String getPhiNom() {
        return this.phiNom;
    }

    public void setPhiNom(String phiNom) {
        this.phiNom = phiNom;
    }

    @Column(name = "PHI_PAP", length = 50)
    public String getPhiPap() {
        return this.phiPap;
    }

    public void setPhiPap(String phiPap) {
        this.phiPap = phiPap;
    }

    @Column(name = "PHI_SAP", length = 50)
    public String getPhiSap() {
        return this.phiSap;
    }

    public void setPhiSap(String phiSap) {
        this.phiSap = phiSap;
    }

    @Column(name = "PHI_SEUNOM", length = 100)
    public String getPhiSeunom() {
        return this.phiSeunom;
    }

    public void setPhiSeunom(String phiSeunom) {
        this.phiSeunom = phiSeunom;
    }
}
